dist: xenial
language: go
go:
  - 1.12.x
env:
  - GO111MODULE=on
git:
  depth: 1
notifications:
  email: false
before_install:
  - go get github.com/mattn/goveralls
install: true
script:
  - $GOPATH/bin/goveralls -service=travis-ci