// Code generated by github.com/mazei513/slice-gen, DO NOT EDIT.
package string

func DeleteString(i int, a []string) []string {
	s := make([]string, i, len(a)-1)
	copy(s, a)
	return append(s, a[i+1:]...)
}
func DeleteRangeString(from, to int, a []string) []string {
	s := make([]string, from, len(a)-(to-from))
	copy(s, a)
	return append(s, a[to+1:]...)
}
func InsertString(i int, o string, a []string) []string {
	var zero string
	s := append(a, zero)
	copy(s[i+1:], a[i:])
	s[i] = o
	return s
}
func PushString(o string, a []string) []string {
	return append(a, o)
}
func PopString(a []string) (string, []string) {
	return a[len(a)-1], append([]string(nil), a[:len(a)-1]...)
}
func UnshiftString(o string, a []string) []string {
	return append([]string{o}, a...)
}
func ShiftString(a []string) (string, []string) {
	return a[0], append([]string(nil), a[1:]...)
}
func FilterString(a []string, f func(string) bool) []string {
	b := make([]string, 0, len(a))
	for _, x := range a {
		if f(x) {
			b = append(b, x)
		}
	}
	return b
}
